# - name: Install AD DS
#   win_command: Install-WindowsFeature -name AD-Domain-Services -IncludeManagementTools
- name: Promote to Domain Controller
  microsoft.ad.domain:
    dns_domain_name: sble.test
    domain_netbios_name: sbletest
    safe_mode_password: Asdf1234
    reboot: true

- name: Update Facts With Domain Membership
  ansible.builtin.gather_facts:
- name: Extract Primary IP address
  set_fact:
    vm_network_ipv4: "{{ (ansible_facts.interfaces | rekey_on_member('macaddress'))[vm_network_mac | upper].ipv4.address }}"
  when: not vm_network_ipv4 | default

- name: Name Secret-Operator User
  set_fact:
    secret_operator_principal: stackable-secret-operator@{{ ansible_facts.domain | upper }}
- name: Create Secret-Operator User
  microsoft.ad.user:
    name: stackable-secret-operator
    sam_account_name: sble-sec-op
    password: Asdf1234
    enabled: true
    identity: CN=stackable-secret-operator,CN=Users,DC=sble,DC=test
    upn: "{{ secret_operator_principal }}"
  register: secret_operator_user
- name: Create Secret-Operator Keytab
  ansible.windows.win_command:
    cmd: ktpass /princ {{ secret_operator_principal }} /out secret-op.kt +rndPass /ptype KRB5_NT_PRINCIPAL /mapuser {{ secret_operator_principal }} /crypto AES256-SHA1
- name: Fetch Secret-Operator Keytab
  ansible.builtin.fetch:
    src: secret-op.kt
    dest: target/
    flat: true

- name: Create SDP Organizational Unit
  microsoft.ad.ou:
    name: SDP
  register: sdp_ou
- name: Grant permissions on SDP Organizational Unit
  ansible.windows.win_shell: |
    # In theory this could be done declaratively by setting the nTSecurityDescriptor before, but that turned out to be a mess...
    Import-Module ActiveDirectory
    $ou_path = "AD:{{ sdp_ou.distinguished_name }}"
    $secretop = [System.Security.Principal.SecurityIdentifier]::New("{{ secret_operator_user.sid }}")
    $acl = Get-ACL -Path $ou_path
    $user_schema_guid = "bf967aba-0de6-11d0-a285-00aa003049e2"
    $password_reset_right_guid = "00299570-246d-11d0-a768-00aa006e0529"
    $ou_create_children_rule = [System.DirectoryServices.ActiveDirectoryAccessRule]::New(
      $secretop,
      [System.DirectoryServices.ActiveDirectoryRights]::CreateChild,
      [System.Security.AccessControl.AccessControlType]::Allow,
      $user_schema_guid,
      [System.DirectoryServices.ActiveDirectorySecurityInheritance]::None
    )
    $ou_reset_passwords_rule = [System.DirectoryServices.ExtendedRightAccessRule]::New(
      $secretop,
      [System.Security.AccessControl.AccessControlType]::Allow,
      $password_reset_right_guid,
      [System.DirectoryServices.ActiveDirectorySecurityInheritance]::Children
    )
    $acl.AddAccessRule($ou_create_children_rule)
    $acl.AddAccessRule($ou_reset_passwords_rule)
    Set-ACL -Path $ou_path -AclObject $acl

- name: Install AD Certificate Services
  ansible.windows.win_feature:
    name:
      - AD-Certificate
      - ADCS-Cert-Authority
    include_management_tools: true
- name: Install ADCS Certificate Authority
  ansible.windows.win_shell: |
    # Try to access certificate authority, should fail
    # iff it is not installed yet
    try {
      Get-CATemplate
    } catch {
      Install-AdcsCertificationAuthority -Force
    }
- name: Export CA Certificate
  ansible.windows.win_command:
    cmd: certutil -f -ca.cert ca.crt
- name: Fetch CA Certificate
  ansible.builtin.slurp:
    src: ca.crt
  register: ca_crt
- name: Convert CA Certificate
  community.crypto.x509_certificate_convert:
    src_content: "{{ ca_crt.content }}"
    src_content_base64: true
    dest_path: target/ca.crt
    format: pem
  delegate_to: localhost
